[package]
name = "modbus-proxy-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["rt", "net", "macros", "io-util", "sync", "time"] }
structopt = "0.3"